apiVersion: v1
kind: Deployment
metadata:
  name: react-jg-app-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: react-jg-app
  template:
    metadata:
      labels:
        app:react-jg-app
    spec:
      containers:
      - name: react-jg-app-deployment
        image: yash5090/react-jg-app:latest
        ports:
        - containerPort: 3000  # Port your application listens on
